### ISSUE TITLE
Graphics and diagrams updates - docs

### ISSUE THREAD

**Issue by joshhus** [hyperledger/fabric#3278] opened 2022-03-09 22:16 UTC
For example, this one is pending / working: 

https://hyperledger-fabric.readthedocs.io/en/release-2.4/getting_started.html

![image](https://user-images.githubusercontent.com/16542757/157545894-b070fee2-75b7-4296-9c02-2244311268c2.png)

Others can be added and worked in this issue.

**Comment by joshhus** [comment] 2022-03-25 20:45
https://github.ibm.com/WCE-ID/Content-Design/issues/386

**Comment by joshhus** [comment] 2022-03-25 21:44
https://github.com/hyperledger/fabric/issues/3278

**Comment by AliakbarETH** [comment] 2023-01-06 10:59
Hi @joshhus I have seen issue number #3278 opened whereas at the bottom the issue is closed.

Is the work done or needs some improvements?

Let me know.

Regards

**Comment by denyeart** [comment] 2023-01-06 16:45
It is resolved now, closing.

**Closed as completed by denyeart** 2023-01-06 16:45 UTC
Labels: documentation
