### ISSUE TITLE
Chaincode Endorsement Policy using Specific Peer(s) 

### ISSUE THREAD

**Issue by manavdeep** [hyperledger/fabric#5047] opened 2024-10-29 10:40 UTC
Hello
So I wanted to know if it is possible to specify signature policy having specific peers. Something like:
--signature-policy "AND('Org1MSP.peer0.org1', 'Org2MSP.peer0.org2')"

Right now I am using Org wide signature policy like:
    --signature-policy "AND('Org1MSP.peer', 'Org2MSP.peer')"

I wanted to restrict it to specific peers. That not possible?

**Comment by bestbeforetoday** [comment] 2024-11-11 15:46
This is a duplicate of the answered issue at hyperledger/fabric-samples#1265

**Closed as completed by bestbeforetoday** 2024-11-11 15:46 UTC
