### ISSUE TITLE
Mac M1 - Peer node container shutdowns when trying to install chain code from the tutorial

### ISSUE THREAD

**Issue by YasirFarhan** [hyperledger/fabric#3702] opened 2022-10-18 19:18 UTC
I am following tutorial here https://hyperledger-fabric.readthedocs.io/en/latest/write_first_app.html
on Mac M1 Max chip
I am using java as language  with bellow steps

>> `./network.sh up createChannel -c mychannel -ca`

>> $ docker ps 
```
CONTAINER ID   IMAGE                               COMMAND                  CREATED              STATUS          PORTS                                                                                                                             NAMES
13bd02b708e4   hyperledger/fabric-tools:latest     "/bin/bash"              46 seconds ago       Up 45 seconds                                                                                                                                     cli
884d0bfe7257   hyperledger/fabric-peer:latest      "peer node start"        46 seconds ago       Up 45 seconds   0.0.0.0:9051->9051/tcp, :::9051->9051/tcp, 7051/tcp, 0.0.0.0:9445->9445/tcp, :::9445->9445/tcp                                    peer0.org2.example.com
8df9710edd85   hyperledger/fabric-orderer:latest   "orderer"                46 seconds ago       Up 45 seconds   0.0.0.0:7050->7050/tcp, :::7050->7050/tcp, 0.0.0.0:7053->7053/tcp, :::7053->7053/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp   orderer.example.com
f1eec9097ce2   hyperledger/fabric-peer:latest      "peer node start"        46 seconds ago       Up 45 seconds   0.0.0.0:7051->7051/tcp, :::7051->7051/tcp, 0.0.0.0:9444->9444/tcp, :::9444->9444/tcp                                              peer0.org1.example.com
25cd4b20a464   hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   About a minute ago   Up 58 seconds   0.0.0.0:9054->9054/tcp, :::9054->9054/tcp, 7054/tcp, 0.0.0.0:19054->19054/tcp, :::19054->19054/tcp                                ca_orderer
9a0f7493a52e   hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   About a minute ago   Up 58 seconds   0.0.0.0:7054->7054/tcp, :::7054->7054/tcp, 0.0.0.0:17054->17054/tcp, :::17054->17054/tcp                                          ca_org1
b5a3c0e770c3   hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   About a minute ago   Up 58 seconds   0.0.0.0:8054->8054/tcp, :::8054->8054/tcp, 7054/tcp, 0.0.0.0:18054->18054/tcp, :::18054->18054/tcp                                ca_org2
```

>> `./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-java/ -ccl java`

error output 
`Query installed on peer0.org1 has failed`
`Deploying chaincode failed`

Bellow output is from `./monitordocker.sh`
```
peer0.org1.example.com|2022-10-18 19:11:42.077 UTC 004b INFO [lifecycle] InstallChaincode -> Successfully installed chaincode with package ID 'basic_1.0:b59806fdb8ae5d17b8efce76b68fdf6bc163d709425574fe3b5b1f63aecd4aec'
peer0.org1.example.com|2022-10-18 19:11:42.079 UTC 004c INFO [endorser] callChaincode -> finished chaincode: _lifecycle duration: 15513ms channel= txID=4f145385
peer0.org1.example.com|2022-10-18 19:11:42.080 UTC 004d INFO [comm.grpc.server] 1 -> unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.peer_address=172.18.0.1:49690 grpc.code=OK grpc.call_duration=16.697164216s
peer0.org2.example.com|2022-10-18 19:11:50.226 UTC 0044 INFO [chaincode.externalbuilder.ccaas_builder] waitForExit -> ::Detect command=detect
peer0.org2.example.com|2022-10-18 19:11:50.235 UTC 0045 INFO [chaincode.externalbuilder.ccaas_builder] waitForExit -> ::Error: chaincode type not supported: java command=detect
   orderer.example.com|2022-10-18 19:11:50.724 UTC 0036 INFO [comm.grpc.server] 1 -> streaming call completed grpc.service=orderer.AtomicBroadcast grpc.method=Deliver grpc.peer_address=172.18.0.5:41848 error="context finished before block retrieved: context canceled" grpc.code=Unknown grpc.call_duration=1m55.692721388s
```

And more output from `./monitordocker.sh`

```
peer0.org2.example.com|2022-10-18 19:11:53.038 UTC 0046 WARN [gossip.comm] func1 -> peer0.org1.example.com:7051, PKIid:55cec609b731437b719d1400c751987c8870f2a4990cd29df4d3dcc0df3ba547 isn't responsive: EOF
peer0.org2.example.com|2022-10-18 19:11:53.040 UTC 0047 WARN [gossip.discovery] expireDeadMembers -> Entering [55cec609b731437b719d1400c751987c8870f2a4990cd29df4d3dcc0df3ba547]
peer0.org2.example.com|2022-10-18 19:11:53.041 UTC 0048 WARN [gossip.discovery] expireDeadMembers -> Closing connection to Endpoint: peer0.org1.example.com:7051, InternalEndpoint: , PKI-ID: 55cec609b731437b719d1400c751987c8870f2a4990cd29df4d3dcc0df3ba547, Metadata:
peer0.org2.example.com|2022-10-18 19:11:53.042 UTC 0049 WARN [gossip.discovery] expireDeadMembers -> Exiting
peer0.org2.example.com|2022-10-18 19:11:53.246 UTC 004a INFO [gossip.channel] reportMembershipChanges -> [[mychannel] Membership view has changed. peers went offline:  [[peer0.org1.example.com:7051 ]] , current view:  []]
peer0.org2.example.com|2022-10-18 19:11:59.517 UTC 004b INFO [lifecycle] InstallChaincode -> Successfully installed chaincode with package ID 'basic_1.0:b59806fdb8ae5d17b8efce76b68fdf6bc163d709425574fe3b5b1f63aecd4aec'
peer0.org2.example.com|2022-10-18 19:11:59.520 UTC 004c INFO [endorser] callChaincode -> finished chaincode: _lifecycle duration: 15119ms channel= txID=2a279d45
peer0.org2.example.com|2022-10-18 19:11:59.522 UTC 004d INFO [comm.grpc.server] 1 -> unary call completed grpc.service=protos.Endorser grpc.method=ProcessProposal grpc.peer_address=172.18.0.1:44624 grpc.code=OK grpc.call_duration=16.168658299s
```

>> Docker ps  output  (one of the peer container is no longer running)
```CONTAINER ID   IMAGE                               COMMAND                  CREATED              STATUS              PORTS                                                                                                                             NAMES
ee564f8e53c6   gliderlabs/logspout                 "/bin/logspout"          About a minute ago   Up About a minute   127.0.0.1:8000->80/tcp                                                                                                            logspout
13bd02b708e4   hyperledger/fabric-tools:latest     "/bin/bash"              3 minutes ago        Up 3 minutes                                                                                                                                          cli
884d0bfe7257   hyperledger/fabric-peer:latest      "peer node start"        3 minutes ago        Up 3 minutes        0.0.0.0:9051->9051/tcp, :::9051->9051/tcp, 7051/tcp, 0.0.0.0:9445->9445/tcp, :::9445->9445/tcp                                    peer0.org2.example.com
8df9710edd85   hyperledger/fabric-orderer:latest   "orderer"                3 minutes ago        Up 3 minutes        0.0.0.0:7050->7050/tcp, :::7050->7050/tcp, 0.0.0.0:7053->7053/tcp, :::7053->7053/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp   orderer.example.com
25cd4b20a464   hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   3 minutes ago        Up 3 minutes        0.0.0.0:9054->9054/tcp, :::9054->9054/tcp, 7054/tcp, 0.0.0.0:19054->19054/tcp, :::19054->19054/tcp                                ca_orderer
9a0f7493a52e   hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   3 minutes ago        Up 3 minutes        0.0.0.0:7054->7054/tcp, :::7054->7054/tcp, 0.0.0.0:17054->17054/tcp, :::17054->17054/tcp                                          ca_org1
b5a3c0e770c3   hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   3 minutes ago        Up 3 minutes        0.0.0.0:8054->8054/tcp, :::8054->8054/tcp, 7054/tcp, 0.0.0.0:18054->18054/tcp, :::18054->18054/tcp                                ca_org2```

**Comment by bestbeforetoday** [comment] 2022-10-19 13:05
This looks to be a duplicate of issue #2994. See [this comment](https://github.com/hyperledger/fabric/issues/2994#issuecomment-1170102505) in that issue for a workaround until native arm64 images are available.

**Comment by YasirFarhan** [comment] 2022-10-20 19:25
> This looks to be a duplicate of issue #2994. See [this comment](https://github.com/hyperledger/fabric/issues/2994#issuecomment-1170102505) in that issue for a workaround until native arm64 images are available.

I have tried this but it is not working for me.

**Comment by bestbeforetoday** [comment] 2022-11-15 14:47
I had a go at reproducing this problem but it works OK for me. For reference, I am using a 16" 2021 Macbook Pro with M1 Max chip, 64GB RAM and MacOS 13.0.1. I do have Rosetta 2 installed, although I don't _think_ that is required. Docker Desktop 4.13.1 with 20GB of RAM allocated to Docker containers, configured to use virtualization.framework and VirtioFS.

Here are the commands used, run from the root directory of a clone of the [fabric-samples](https://github.com/hyperledger/fabric-samples) repository **main** branch:

- `curl --location https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/install-fabric.sh | bash -s d b`
- `docker pull --platform amd64 hyperledger/fabric-nodeenv:2.4`
- `docker pull --platform amd64 hyperledger/fabric-javaenv:2.4`
- `cd test-network`
- `./network.sh up createChannel -c mychannel -ca`
- `./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-java/ -ccl java`

This results in the following output from `docker ps`:
```
CONTAINER ID   IMAGE                                                                                                                                                                    COMMAND                  CREATED          STATUS          PORTS                                                                    NAMES
7628a3aac69d   dev-peer0.org2.example.com-basic_1.0-6a793e21d3b559f9a82cc8068b67a534ab6fe8de78e3d005921a9cc4239331a7-d70889adbbe5c96eed0a89e1ab366c2dba699f72af68171ab18db10996a23eb0   "/root/chaincode-jav…"   9 minutes ago    Up 9 minutes                                                                             dev-peer0.org2.example.com-basic_1.0-6a793e21d3b559f9a82cc8068b67a534ab6fe8de78e3d005921a9cc4239331a7
66e7171f44ec   dev-peer0.org1.example.com-basic_1.0-6a793e21d3b559f9a82cc8068b67a534ab6fe8de78e3d005921a9cc4239331a7-183254c9854b0d8c5e45df7f0b99a5d65971ef07da2538aa2c79112649fd2aac   "/root/chaincode-jav…"   9 minutes ago    Up 9 minutes                                                                             dev-peer0.org1.example.com-basic_1.0-6a793e21d3b559f9a82cc8068b67a534ab6fe8de78e3d005921a9cc4239331a7
c5b7be9b6ff5   hyperledger/fabric-tools:latest                                                                                                                                          "/bin/bash"              10 minutes ago   Up 10 minutes                                                                            cli
421c79bea721   hyperledger/fabric-peer:latest                                                                                                                                           "peer node start"        10 minutes ago   Up 10 minutes   0.0.0.0:7051->7051/tcp, 0.0.0.0:9444->9444/tcp                           peer0.org1.example.com
6f7873e67c10   hyperledger/fabric-orderer:latest                                                                                                                                        "orderer"                10 minutes ago   Up 10 minutes   0.0.0.0:7050->7050/tcp, 0.0.0.0:7053->7053/tcp, 0.0.0.0:9443->9443/tcp   orderer.example.com
a2451d600946   hyperledger/fabric-peer:latest                                                                                                                                           "peer node start"        10 minutes ago   Up 10 minutes   0.0.0.0:9051->9051/tcp, 7051/tcp, 0.0.0.0:9445->9445/tcp                 peer0.org2.example.com
fc0abfded281   hyperledger/fabric-ca:latest                                                                                                                                             "sh -c 'fabric-ca-se…"   11 minutes ago   Up 11 minutes   0.0.0.0:9054->9054/tcp, 7054/tcp, 0.0.0.0:19054->19054/tcp               ca_orderer
832dbc8b2d30   hyperledger/fabric-ca:latest                                                                                                                                             "sh -c 'fabric-ca-se…"   11 minutes ago   Up 11 minutes   0.0.0.0:7054->7054/tcp, 0.0.0.0:17054->17054/tcp                         ca_org1
84bf741f745d   hyperledger/fabric-ca:latest                                                                                                                                             "sh -c 'fabric-ca-se…"   11 minutes ago   Up 11 minutes   0.0.0.0:8054->8054/tcp, 7054/tcp, 0.0.0.0:18054->18054/tcp               ca_org2
```

Again for reference, these are the Docker images used:

```
REPOSITORY                   TAG       IMAGE ID       CREATED         SIZE
hyperledger/fabric-tools     2.4       545af418d284   2 weeks ago     489MB
hyperledger/fabric-tools     2.4.7     545af418d284   2 weeks ago     489MB
hyperledger/fabric-tools     latest    545af418d284   2 weeks ago     489MB
hyperledger/fabric-peer      2.4       d77dd7cfbcd7   2 weeks ago     64.2MB
hyperledger/fabric-peer      2.4.7     d77dd7cfbcd7   2 weeks ago     64.2MB
hyperledger/fabric-peer      latest    d77dd7cfbcd7   2 weeks ago     64.2MB
hyperledger/fabric-orderer   2.4       77c489caa81b   2 weeks ago     36.7MB
hyperledger/fabric-orderer   2.4.7     77c489caa81b   2 weeks ago     36.7MB
hyperledger/fabric-orderer   latest    77c489caa81b   2 weeks ago     36.7MB
hyperledger/fabric-ccenv     2.4       4eb7ee7f4af5   2 weeks ago     520MB
hyperledger/fabric-ccenv     2.4.7     4eb7ee7f4af5   2 weeks ago     520MB
hyperledger/fabric-ccenv     latest    4eb7ee7f4af5   2 weeks ago     520MB
hyperledger/fabric-baseos    2.4       b20d2dde6941   2 weeks ago     6.82MB
hyperledger/fabric-baseos    2.4.7     b20d2dde6941   2 weeks ago     6.82MB
hyperledger/fabric-baseos    latest    b20d2dde6941   2 weeks ago     6.82MB
hyperledger/fabric-ca        1.5       93f19fa873cb   4 months ago    76.5MB
hyperledger/fabric-ca        1.5.5     93f19fa873cb   4 months ago    76.5MB
hyperledger/fabric-ca        latest    93f19fa873cb   4 months ago    76.5MB
hyperledger/fabric-nodeenv   2.4       31959bcd1525   6 months ago    341MB
hyperledger/fabric-javaenv   2.4       f431a905b935   11 months ago   396MB
```

**Comment by denyeart** [comment] 2023-02-01 12:50
@YasirFarhan v2.5.0-beta has been published and includes support for arm64 images and binaries. Can you try it out on v2.5.0-beta and confirm the issues are resolved?

**Comment by denyeart** [comment] 2023-02-08 04:57
No response, closing, please re-open if you have more information.

**Closed as completed by denyeart** 2023-02-08 04:57 UTC
